// Code generated by protoc-gen-go. DO NOT EDIT.
// source: generator.proto

package generator

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartSpec struct {
	NumOfMessagePerSecond int32    `protobuf:"fixed32,1,opt,name=num_of_message_per_second,json=numOfMessagePerSecond,proto3" json:"num_of_message_per_second,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *StartSpec) Reset()         { *m = StartSpec{} }
func (m *StartSpec) String() string { return proto.CompactTextString(m) }
func (*StartSpec) ProtoMessage()    {}
func (*StartSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_25df606994424d60, []int{0}
}

func (m *StartSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartSpec.Unmarshal(m, b)
}
func (m *StartSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartSpec.Marshal(b, m, deterministic)
}
func (m *StartSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartSpec.Merge(m, src)
}
func (m *StartSpec) XXX_Size() int {
	return xxx_messageInfo_StartSpec.Size(m)
}
func (m *StartSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_StartSpec.DiscardUnknown(m)
}

var xxx_messageInfo_StartSpec proto.InternalMessageInfo

func (m *StartSpec) GetNumOfMessagePerSecond() int32 {
	if m != nil {
		return m.NumOfMessagePerSecond
	}
	return 0
}

// A Sensor is generated in response to a Start rpc
//
// It contains value, type, and identifier to be later sent to processor
type Sensor struct {
	SensorValue          float32              `protobuf:"fixed32,1,opt,name=sensor_value,json=sensorValue,proto3" json:"sensor_value,omitempty"`
	SensorType           string               `protobuf:"bytes,2,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	Id1                  string               `protobuf:"bytes,3,opt,name=id1,proto3" json:"id1,omitempty"`
	Id2                  int32                `protobuf:"fixed32,4,opt,name=id2,proto3" json:"id2,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Sensor) Reset()         { *m = Sensor{} }
func (m *Sensor) String() string { return proto.CompactTextString(m) }
func (*Sensor) ProtoMessage()    {}
func (*Sensor) Descriptor() ([]byte, []int) {
	return fileDescriptor_25df606994424d60, []int{1}
}

func (m *Sensor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sensor.Unmarshal(m, b)
}
func (m *Sensor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sensor.Marshal(b, m, deterministic)
}
func (m *Sensor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sensor.Merge(m, src)
}
func (m *Sensor) XXX_Size() int {
	return xxx_messageInfo_Sensor.Size(m)
}
func (m *Sensor) XXX_DiscardUnknown() {
	xxx_messageInfo_Sensor.DiscardUnknown(m)
}

var xxx_messageInfo_Sensor proto.InternalMessageInfo

func (m *Sensor) GetSensorValue() float32 {
	if m != nil {
		return m.SensorValue
	}
	return 0
}

func (m *Sensor) GetSensorType() string {
	if m != nil {
		return m.SensorType
	}
	return ""
}

func (m *Sensor) GetId1() string {
	if m != nil {
		return m.Id1
	}
	return ""
}

func (m *Sensor) GetId2() int32 {
	if m != nil {
		return m.Id2
	}
	return 0
}

func (m *Sensor) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*StartSpec)(nil), "generator.StartSpec")
	proto.RegisterType((*Sensor)(nil), "generator.Sensor")
}

func init() { proto.RegisterFile("generator.proto", fileDescriptor_25df606994424d60) }

var fileDescriptor_25df606994424d60 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x3b, 0xfd, 0x07, 0xb9, 0xfd, 0xa0, 0x9f, 0x83, 0x4a, 0x8c, 0x8b, 0xd6, 0xac, 0xba,
	0x4a, 0xb5, 0xba, 0xc8, 0x0b, 0x14, 0x57, 0xa2, 0x24, 0xc5, 0xed, 0x90, 0xb6, 0x37, 0xa1, 0xd0,
	0xc9, 0x0c, 0x33, 0x13, 0x21, 0xf8, 0x46, 0x3e, 0xa5, 0x64, 0xc6, 0xa4, 0xa2, 0xb8, 0x3b, 0xf9,
	0x9d, 0x13, 0xe6, 0x9e, 0x03, 0xd3, 0x02, 0x4b, 0x54, 0x99, 0x11, 0x2a, 0x92, 0x4a, 0x18, 0x41,
	0xbd, 0x0e, 0x04, 0xd7, 0x85, 0x10, 0xc5, 0x11, 0x97, 0xd6, 0xd8, 0x56, 0xf9, 0x12, 0xb9, 0x34,
	0xb5, 0xcb, 0x05, 0xb3, 0x9f, 0xa6, 0x39, 0x70, 0xd4, 0x26, 0xe3, 0xd2, 0x05, 0xc2, 0x35, 0x78,
	0xa9, 0xc9, 0x94, 0x49, 0x25, 0xee, 0x68, 0x0c, 0x57, 0x65, 0xc5, 0x99, 0xc8, 0x19, 0x47, 0xad,
	0xb3, 0x02, 0x99, 0x44, 0xc5, 0x34, 0xee, 0x44, 0xb9, 0xf7, 0xc9, 0x9c, 0x2c, 0xa6, 0xc9, 0x45,
	0x59, 0xf1, 0xe7, 0xfc, 0xc9, 0xd9, 0x2f, 0xa8, 0x52, 0x6b, 0x86, 0x1f, 0x04, 0xc6, 0x29, 0x96,
	0x5a, 0x28, 0x7a, 0x03, 0xff, 0xb4, 0x55, 0xec, 0x2d, 0x3b, 0x56, 0x68, 0xff, 0xeb, 0x27, 0x13,
	0xc7, 0x5e, 0x1b, 0x44, 0x67, 0xf0, 0xf5, 0xc9, 0x4c, 0x2d, 0xd1, 0xef, 0xcf, 0xc9, 0xc2, 0x4b,
	0xc0, 0xa1, 0x4d, 0x2d, 0x91, 0xfe, 0x87, 0xc1, 0x61, 0x7f, 0xe7, 0x0f, 0xac, 0xd1, 0x48, 0x47,
	0x56, 0xfe, 0xd0, 0x1e, 0xd1, 0x48, 0x1a, 0x83, 0xd7, 0x95, 0xf1, 0x47, 0x73, 0xb2, 0x98, 0xac,
	0x82, 0xc8, 0xd5, 0x8d, 0xda, 0xba, 0xd1, 0xa6, 0x4d, 0x24, 0xa7, 0xf0, 0xea, 0x1d, 0xbc, 0xc7,
	0x76, 0x3e, 0xfa, 0x00, 0x23, 0x3b, 0x00, 0x3d, 0x8f, 0x4e, 0x23, 0x77, 0x93, 0x04, 0x67, 0xdf,
	0xa9, 0x3d, 0x30, 0xec, 0xdd, 0x12, 0x1a, 0xc3, 0x30, 0x35, 0x42, 0xd2, 0xcb, 0x5f, 0x2f, 0xae,
	0x9b, 0xf5, 0x83, 0x3f, 0x78, 0xd8, 0xdb, 0x8e, 0x2d, 0xb9, 0xff, 0x0c, 0x00, 0x00, 0xff, 0xff,
	0xf6, 0xc5, 0x37, 0x07, 0xd3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GeneratorClient is the client API for Generator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeneratorClient interface {
	// Start Generating stream of sensor
	Start(ctx context.Context, in *StartSpec, opts ...grpc.CallOption) (Generator_StartClient, error)
	// Stop Generating stream of sensor
	Stop(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type generatorClient struct {
	cc *grpc.ClientConn
}

func NewGeneratorClient(cc *grpc.ClientConn) GeneratorClient {
	return &generatorClient{cc}
}

func (c *generatorClient) Start(ctx context.Context, in *StartSpec, opts ...grpc.CallOption) (Generator_StartClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Generator_serviceDesc.Streams[0], "/generator.Generator/Start", opts...)
	if err != nil {
		return nil, err
	}
	x := &generatorStartClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Generator_StartClient interface {
	Recv() (*Sensor, error)
	grpc.ClientStream
}

type generatorStartClient struct {
	grpc.ClientStream
}

func (x *generatorStartClient) Recv() (*Sensor, error) {
	m := new(Sensor)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *generatorClient) Stop(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/generator.Generator/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneratorServer is the server API for Generator service.
type GeneratorServer interface {
	// Start Generating stream of sensor
	Start(*StartSpec, Generator_StartServer) error
	// Stop Generating stream of sensor
	Stop(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedGeneratorServer can be embedded to have forward compatible implementations.
type UnimplementedGeneratorServer struct {
}

func (*UnimplementedGeneratorServer) Start(req *StartSpec, srv Generator_StartServer) error {
	return status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedGeneratorServer) Stop(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}

func RegisterGeneratorServer(s *grpc.Server, srv GeneratorServer) {
	s.RegisterService(&_Generator_serviceDesc, srv)
}

func _Generator_Start_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartSpec)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeneratorServer).Start(m, &generatorStartServer{stream})
}

type Generator_StartServer interface {
	Send(*Sensor) error
	grpc.ServerStream
}

type generatorStartServer struct {
	grpc.ServerStream
}

func (x *generatorStartServer) Send(m *Sensor) error {
	return x.ServerStream.SendMsg(m)
}

func _Generator_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/generator.Generator/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorServer).Stop(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Generator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "generator.Generator",
	HandlerType: (*GeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stop",
			Handler:    _Generator_Stop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Start",
			Handler:       _Generator_Start_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "generator.proto",
}
